# Generated by Django 4.1.1 on 2023-01-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images_for_image_app/%Y/%m/%d/'),
        ),
    ]
